---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Import VPC Setup Variable
      include_vars: vars/vpc_setup

    - name: Import VPC Setup Variable
      include_vars: vars/vpc-output_vars

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: ./bastion-key.pem
        mode: 0600
      when: key_out.changed
    
    - name: Create Security Group for Bastion Groups
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Check if Bastion Host already exists
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "Bastion_Host"
          "tag:Project": "Vprofile"
          "tag:Owner": "Shariq"
        instance_states: [running]
      register: existing_instances

    - name: Creating Bastion Host
      ec2_instance:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}" 
        wait: yes
        wait_timeout: 300
        tags:
          Name: "Bastion_Host"
          Project: Vprofile
          Owner: Shariq
        vpc_subnet_id: "{{ pubsub1id }}"
      register: bastionHost_out
      when: existing_instances.instances | length == 0

    - name: Insert/Update "BastionSGid" in vars/vpc-output_vars
      blockinfile:
        path: vars/vpc-output_vars
        backup: yes
        block: |
          BastionSGid: {{BastionSG_out.group_id}}