---
- name: Setup mysql with accounts db and remote login
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: Installing Mysql Service and Dependencies
      package:
        name: "{{item}}"
        state: present
        update_cache: yes
        cache_valid_time: 86400
      loop:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - python3-mysqldb
        - libmysqlclient-dev
      ignore_errors: yes
      tags:
        - package

    - name: Start & Enable Mysql service
      service: 
        name: mysql
        state: started
        enabled: yes
      tags:
        - svc

    - name: Creating Mysql user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Create accounts db
      mysql_db:
        name: "{{dbname}}"
        state: present

    - name: Enable Remote login to mysql svc
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql
      tags:
        - conf
    
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
